Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1,11 +1,10 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: CONEXAO SSHPLUS MANAGER
-#	DESENVOLVIDO POR:	CRAZY_VPN
-#	DATA ATUALIZACAO:	16-03-2021 
-#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
-#	CANAL TELEGRAM:	http://t.me/sshplus
+#	@kiritosshxd
 #====================================================
+cor1='\033[41;1;37m'
+cor2='\033[44;1;37m'
+scor='\033[0m'
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@CRAZY_VPN" ]] && {
 	ram1=$(free -h | grep -i mem | awk {'print $2'})
 	ram2=$(free -h | grep -i mem | awk {'print $4'})
@@ -460,7 +459,118 @@
 			}
 		fi
 	}
+    	fun_chisel() {
+		clear
+		echo -e "\E[44;1;37m            GERENCIAR CHISEL             \E[0m"
+		echo ""
+		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHISEL\033[0m"
+		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREINICIAR CHISEL\033[0m"
+		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+		echo ""
+		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+		read resposta
+		if [[ "$resposta" = '1' ]]; then
+			if netstat -nltp | grep 'docker' 1>/dev/null 2>/dev/null; then
+				clear
+				echo -e "\E[41;1;37m             CHISEL              \E[0m"
+				echo ""
+				fun_chiseloff() {
+					docker stop chisel
+                    docker rm chisel
 
+				}
+				echo -e "\033[1;32mDESATIVANDO CHISEL\033[1;33m"
+				echo ""
+				fun_bar 'fun_chiseloff'
+				echo ""
+				echo -e "\033[1;32mCHISEL DESATIVADO COM SUCESSO!\033[1;33m"
+				sleep 3
+				fun_chisel
+			else
+                clear
+                echo -e "\n\033[1;32mINSTALANDO O CHISEL !\033[1;33m"
+				echo ""
+				fun_bar 'apt-get update -y' 'apt-get install docker -y'                
+				clear
+				echo -e "\E[44;1;37m             CHISEL              \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					sleep 3
+					clear
+					fun_chisel
+				}
+				verif_ptrs $porta
+                echo -ne "\033[1;32mNome do usuário:\033[1;37m ";read username
+                [[ -z $username ]] && {
+                    echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
+                    fun_chisel
+                }
+                [[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
+                    echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
+                    fun_chisel
+                }
+                sizemin=$(echo ${#username})
+                [[ $sizemin -lt 2 ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
+                    echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+                    fun_chisel
+                }
+                sizemax=$(echo ${#username})
+                [[ $sizemax -gt 10 ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
+                    echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
+                    fun_chisel
+                }
+                echo -ne "\033[1;32mSenha:\033[1;37m ";read password
+                [[ -z $password ]] && {
+                    echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
+                    fun_chisel 
+                }
+                sizepass=$(echo ${#password})
+                [[ $sizepass -lt 4 ]] && {
+                    echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
+                    fun_chisel        
+                }
+                echo -e "\n\033[1;32mCONFIGURANDO CHISEL !\033[0m"
+				echo ""
+                fun_inichisel() {
+                    docker run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
+                }
+                fun_bar 'fun_inichisel'
+                echo -e "\n\033[1;32mCHISEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m${porta}\033[0m"
+				sleep 3
+				clear
+				fun_chisel
+            fi
+        elif [[ "$resposta" = '2' ]]; then
+            clear
+            echo -e "\n\033[1;32mREINICIANDO CHISEL !\033[1;33m"
+			echo ""
+            fun_attchisel() {
+                docker restart chisel
+            }
+            fun_attchisel
+            clear
+            echo -e "\n\033[1;32mCHISEL REINICIANDO COM SUCESSO !\033[1;33m"
+            sleep 1
+            fun_chisel
+        elif [[ "$resposta" = '0' ]]; then
+			echo ""
+			echo -e "\033[1;31mRetornando...\033[0m"
+			sleep 1
+			fun_conexao
+		else
+			echo ""
+			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			sleep 1
+			fun_socks
+		fi
+    }
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
 			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
@@ -1824,11 +1934,16 @@ exit 0' >$RCLOCAL
 			clear
 			echo -e "\E[44;1;37m                MODO DE CONEXAO                 \E[0m\n"
 			echo -e "\033[1;32mSERVICO: \033[1;33mOPENSSH \033[1;32mPORTA: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "
-			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+			[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
 				sts8="\033[1;32m◉ "
 			} || {
 				sts8="\033[1;31m○ "
 			}
+			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+				sts9="\033[1;32m◉ "
+			} || {
+				sts9="\033[1;31m○ "
+			}            
 			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mSERVICO: \033[1;33mSSLH: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts7="\033[1;32m◉ "
@@ -1876,8 +1991,9 @@ exit 0' >$RCLOCAL
 [\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mPROXY SOCKS $sts4\033[1;31m
 [\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
 [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH MULTIPLEX $sts7\033[1;31m
-[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts8\033[1;31m
-[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
+[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHISEL $sts8\033[1;31m
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts9\033[1;31m
+[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
 [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 			echo ""
 			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
@@ -1910,9 +2026,12 @@ exit 0' >$RCLOCAL
 				fun_sslh
 				;;
 		    8 | 08)
+				fun_chisel
+                ;;              
+		    9 | 09)
 				slow_dns
 				;;
-			9 | 09)
+			10 | 10)
 				menu
 				;;
 			0 | 00)
